### ISSUE TITLE
Question: how to inject a class into a context?

### ISSUE THREAD

**Issue by walterdolce** [jakzal/BehatNoExtension#9]
By following the brief documentation in the README.md it is not clear whether and how it is possible to inject components into a context constructor (by the look of the `*.feature` files it seems it is possible though).
- How can someone inject an interface in a context which is mapped against a concrete implementation? 
- If an interface to be injected in a context has collaborators, how should those be specified?

Please note the use of any Symfony-related component is _not_ assumed here. I'm talking plain POPOs needed to ensure the test suite's codebase is well structured and for its components to be reusable.

Thanks!

**Comment by jakzal** [comment]
At the moment you need to provide an argument resolver, to resolve context arguments to services.

I do have such an argument resolver already written, which I've used on several projects, and I will make it part of this extension :)

**Comment by walterdolce** [comment]
When when when when :)

**Comment by jakzal** [comment]
For other's reference, an example is here: https://github.com/jakzal/BehatNoExtension/pull/2#issuecomment-259371761

I will provide a built in support though :)

**Comment by walterdolce** [comment]
Great! I'd say let's keep this open until it's added.
Let me know if/how I can help ;)
